### PR TITLE
Add try block in RepoModel init

### PR DESCRIPTION
**Pull request by ronentk**
To ignore bad annotation fails (instead of failing init)

### CODE REVIEW

**Comment by stephantul** [comment]
Hi @ronentk, Thanks for the PR! 

I see that it also includes a change unrelated to the repomodel issue (the addition to event edges in `b62f020`). Could you remove that from this PR, and put it in a separate PR?

The `try: except:` block you added should test for a specific exception, or a set of them, according to PEP8: see [here](https://www.python.org/dev/peps/pep-0008/#programming-recommendations). Narrowing that down would also be useful.

An example of a case we don't want to catch is a MemoryError, which might happen when a user loads too many annotations in limited memory. If that were to happen, we would not want to continue, since we'd get the MemoryError for each of the following annotations as well.

**Comment by stephantul** [comment]
I'd also be a fan of the addition of a `strict` mode. We could add a boolean argument to the loading function, that, when set to `True`, will still cause the exception to be reraised after printing. 

Basically, what I'm afraid of here is that some users will miss annotations because they don't look at stdout, and don't realize that information is being left out. Let me know what you think.

**Review by stephantul — CHANGES_REQUESTED** [review]
line 43 needs to specify the exceptions a bit more. Optionally, add an argument (`strict`) or something that does or does not reraise the exception.

**Comment by ronentk** [comment]
Hi @stephantul, thanks for the feedback. I limited the exception to be more specific (just for `KeyError`s).

**Review by stephantul — APPROVED** [review]
LGTM

**Comment by stephantul** [comment]
@ronentk, I approved of the changes. Thanks for the help, I hope the software has been useful to you.

**Comment by ronentk** [comment]
> @ronentk, I approved of the changes. Thanks for the help, I hope the software has been useful to you.

Indeed @stephantul, saved me a lot of extra work. Thanks :)

**Pull request merged**
