### PR TITLE
Brooks/installable

### PR DESCRIPTION
**Pull request by andrewbrooks-o**
Making repo installable python package

### CODE REVIEW

**Comment by stephantul** [comment]
Thanks! I'll check it out ASAP.

**Review by stephantul — CHANGES_REQUESTED** [review]
The license of the repo recently changed (is now GPL v3.0). The README still erroneously read MIT, which has now been corrected

Please use semantic versioning (i.e. three numbers). The current version is `1.0.0`.

The author field should not be your, but should either be my name (`Stéphan Tulkens`), or  (`Computational Psycholinguistics Research Group (CLiPS)`).

**Comment by andrewbrooks-o** [comment]
@stephantul - thanks for the review!  In truth, I actually accidentally made this PR to the main repo instead of my fork.  In any case, glad you'd like to bring these changes in : ) Made the changes requested.

**Review by stephantul — APPROVED** [review]

**Comment by stephantul** [comment]
@andrewbrooks-o ha, a happy accident! We always welcome PRs, so if you find some other new stuff, feel free to contribute 🥇

**Pull request merged**
